name: user_eventticket
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  supabase_flutter: ^2.8.3
  intl: ^0.20.2
  file_picker: ^9.0.2
  image_picker: ^1.1.2
  path: ^1.9.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
